name: issue552

on: 
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true
    - name: Create cache directory if missing
      run: mkdir -p C:\Users\runneradmin\AppData\Local\go-build
    - name: Install Dependencies
      run: |
          go mod download
        
